### ISSUE TITLE
Response in ended before the catch in `RequestListener`

### ISSUE THREAD

**Issue by asadhazara** [enisdenjo/graphql-sse#13]
In the following example the server is not returning 500 _Internal Server Error_. Instead the server throws an error (`Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client`) and the process is killed. 

```ts
import http from 'http';
import { createHandler } from 'graphql-sse';

const handler = createHandler({
  ...
  onNext: () => {
    throw new Error('Not implemented');
  },
});

http.createServer(async (req, res) => {
  try {
    await handler(req, res);
  } catch (err) {
    res.writeHead(500, 'Internal Server Error').end();
  }
});
```

**Comment by enisdenjo** [comment]
Hmm, I couldn't manage to replicate your issue, [I've added tests describing your case](https://github.com/enisdenjo/graphql-sse/commit/3bb5aafda1c341c8dd631a4d1dc37a303fc9f57c), and they pass.

Can you elaborate further? Which version are you using? How are you connecting to the server? Which client are you using?

Ideally a full repro would be perfect and much appreciated!

**Comment by enisdenjo** [comment]
Ah, ok, I misread - the error is thrown properly, but you have problems writing the headers.

The SSE headers are **already written and flushed** at the point where `onNext` is reached. Writing a `200: OK` is necessary in order to establish an SSE connection.

**Comment by asadhazara** [comment]
If I want to write a different head, what are the options? For instance, I would like to send a 500 when something goes wrong.

**Comment by enisdenjo** [comment]
You cannot write a different header. As mentioned before, it is already written and flushed at that point.

You can only leave a log on your server and fix the `onNext` handler.

**Comment by enisdenjo** [comment]
Since re-writing the header is not possible, you can catch the error in `onNext` and populate the `errors` GraphQL result field.

Something around the edges:
```ts
import http from 'http';
import { createHandler } from 'graphql-sse';

const handler = createHandler({
  // ... your other options ...
  onNext: () => {
    try {
      mightThrowAnError();
    } catch (err) {
      return {
        errors: [new GraphQLError(err)],
      };
    }
  },
});

http.createServer(async (req, res) => {
  try {
    await handler(req, res);
  } catch (err) {
    if (!res.headersSent) {
      res.writeHead(500, 'Internal Server Error').end();
    } else {
      console.error('Internal Server Error', err);
    }
  }
});
```

**Comment by asadhazara** [comment]
Thank you @enisdenjo! The example I have used is directly copied from the JSDoc for the `Handler`. I have submitted a PR for this.
