### ISSUE TITLE
Timeout parameter ?

### ISSUE THREAD

**Issue by LadghemSaid** [enisdenjo/graphql-sse#17]
Hi thanks for this implementation of SSE,
i cant find any way to close the connection after some timeout delay is it even possible ?

**Comment by enisdenjo** [comment]
You mean a timeout delay like [`graphql-ws`'s client `lazyCloseTimeout` option](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.ClientOptions.md#lazyclosetimeout)? Meant to be used in combination with the `lazy` option (so only in `singleConnection` mode) - how long should the client wait before closing the connection after the last operation has completed?

**Comment by LadghemSaid** [comment]
Thanks for the reply,
yes excatly i need this, i've tried using the client.dispose() with a
setTimeout but i wonder if there is a better way ?

Le lun. 28 févr. 2022 à 17:46, Denis Badurina ***@***.***> a
écrit :

**Comment by LadghemSaid** [comment]
By any chance do you have any idea on a better pattern ? i've also tried to unsubscribe the subscribeToMore but it doesnt seem to work well

**Comment by enisdenjo** [comment]
I will add a  [`graphql-ws`'s client `lazyCloseTimeout` option](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.ClientOptions.md#lazyclosetimeout) equivalent for `graphql-sse`.

However, I don't have enough free time currently to work on this, sorry. I hope my time frees up in the following days.
