### ISSUE TITLE
Client doesn't report the server abruptly going away in the middle of event emission (only in NodeJS)

### ISSUE THREAD

**Issue by enisdenjo** [enisdenjo/graphql-sse#22]
Kudos, and big thanks, to @brentmjohnson for discovering this bug over at #21!

As per https://github.com/enisdenjo/graphql-sse/issues/22#issuecomment-1143647949, this issue seems to be exclusive to NodeJS environments.

**Expected Behaviour**

If the server goes away abruptly during event emission, the client reports the error to the sink.

**Actual Behaviour**

If the server goes away abruptly during event emission, the client gets stuck and the sink is never finalised.

**Comment by enisdenjo** [comment]
Hmm, seems like this bug is exclusive to NodeJS. I've tried replicating the same behaviour in the browser, but it fails immediately when the server gets killed. Here are my repro steps:

1. Write up a `test.mjs` server:
```ts
import { GraphQLSchema, GraphQLObjectType, GraphQLString } from 'graphql';
import http from 'http';
import { createHandler } from './lib/index.mjs';

const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    fields: {
      hello: {
        type: GraphQLString,
        resolve: () => 'world',
      },
    },
  }),
  subscription: new GraphQLObjectType({
    name: 'Subscription',
    fields: {
      greetings: {
        type: GraphQLString,
        subscribe: async function* () {
          for (const hi of ['Hi', 'Bonjour', 'Hola', 'Ciao', 'Zdravo']) {
            yield { greetings: hi };
            await new Promise((resolve) => setTimeout(resolve, 3000));
          }
        },
      },
    },
  }),
});

const handler = createHandler({ schema });

const server = http.createServer(async (req, res) => {
  if (!req.url.startsWith('/graphql/stream')) {
    return res.writeHead(404).end();
  }

  try {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', '*');
    res.setHeader('Access-Control-Allow-Headers', '*');
    if (req.method === 'OPTIONS') {
      // preflight
      return res.writeHead(204).end();
    }

    return await handler(req, res);
  } catch (err) {
    console.error(err);
    if (!res.headersSent) {
      res.writeHead(500);
    }
    return res.end();
  }
});

server.listen(4000);
console.log('Listening to port 4000');
```
2. `node test.mjs`
3. Load GraphiQL in the browser using [this gist](https://gist.github.com/enisdenjo/d7bc1a013433502349d2763c3d2f2b79)
4. Subscribe to greetings:
```gql
subscription {
  greetings
}
```
5. Kill the server whenever after the 1st event emission
6. The browser immediately reports `POST http://localhost:4000/graphql/stream net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)` to the console (also when running the client in "single connection mode")

I've Googled around but couldn't find any clues about why this test fails: https://github.com/enisdenjo/graphql-sse/blob/72d284aef0deb6310fea41804f189669f7a8082e/src/__tests__/client.ts#L176-L194

Could it be `node-fetch` or just Node itself? Any ideas @brentmjohnson?

**Comment by brentmjohnson** [comment]
Sure I'll take a look @enisdenjo - will let you know what I find.

**Comment by enisdenjo** [comment]
I am closing this issue with https://github.com/enisdenjo/graphql-sse/commit/8f002f190b236bba8932b1e47ea5b40810a42b4d because the issue stems from v2 of `node-fetch` and is fixed with v3.

See https://github.com/node-fetch/node-fetch/issues/1604.

**Comment by brentmjohnson** [comment]
> I am closing this issue with [8f002f1](https://github.com/enisdenjo/graphql-sse/commit/8f002f190b236bba8932b1e47ea5b40810a42b4d) because the issue stems from v2 of `node-fetch` and is fixed with v3.
> 
> See [node-fetch/node-fetch#1604](https://github.com/node-fetch/node-fetch/issues/1604).

@enisdenjo what a great find. Thank you so much for your persistence in identifying the resolution!
