### ISSUE TITLE
Reconnection not working on Chrome

### ISSUE THREAD

**Issue by Emilios1995** [enisdenjo/graphql-sse#27]
**Screenshot**
<img width="809" alt="Screen Shot 2022-06-08 at 18 22 17" src="https://user-images.githubusercontent.com/12430923/172733630-2f65d8d7-1a01-4011-811e-cf99a79cbbb2.png">

**Expected Behaviour**
Disconnecting the client from the internet and the reconnecting should cause it to reconnect when `graphql-sse` performs a re-connection attempt. 

I'm using a mostly standard setup of the `graphql-sse` client with Relay.

**Actual Behaviour**
I see an error ending up in the console as in the screenshot. It's not being handled by `graphql-sse` and reconnecting. The error ends up at the top of my sink. 

Firefox and Edge actually work for me. The problem is in Chrome and Safari.

**Debug Information**
I discovered that the error surfaces in [this](https://github.com/enisdenjo/graphql-sse/blob/master/src/client.ts#L442-L451) `catch` clause in the form of a `TypeError` with the message: `network error` (which is standard with the Fetch API AFAIK) but since it was never converted to a `NetworkError`, it doesn't trigger a retry. 

I dug deeper to find the source of the error and see why it wasn't converted to `NetworkError` and noticed that it was thrown from the `toAsyncIterator` function, from which apparently you didn't anticipate network errors occurring. 

**Further Information**
- I tried disabling the QUIQ protocol via a Chrome flag and the console error changes to `ERR_NETWORK_CHANGED`

Pleas let me know if you aren't able to reproduce and whether I can help with anything.

**Comment by enisdenjo** [comment]
Great catch! I've noticed it also with https://github.com/enisdenjo/graphql-sse/issues/22#issuecomment-1143647949 but you beat me to creating an issue.

Thanks for reporting! I'll take care of it soon. 👍

**Comment by enisdenjo** [comment]
Seems like this issue is still present in Safari and Firefox. 
- Safari because when the server terminates, the [connection completes (does not error out)](https://github.com/enisdenjo/graphql-sse/blob/3f516d7c3677985171250707983f84be39564030/src/client.ts#L740)
- Firefox because the error message does not contain the keyword "network"

**Comment by enisdenjo** [comment]
Firefox is now handled with https://github.com/enisdenjo/graphql-sse/commit/054f16b7bfb7cc6928dd538de3029719591c9ebe.
