### ISSUE TITLE
Http2 Example req res params not accepted

### ISSUE THREAD

**Issue by elritz** [enisdenjo/graphql-sse#38]
**Screenshot**
Visualising is always helpful.
![Screenshot 2022-12-06 at 10 20 03 AM](https://user-images.githubusercontent.com/20426361/205951868-adbf90f3-3ed1-4cbe-85a5-31b5cdea07a6.png)

**Expected Behaviour**
I expected this to work out of the box, it is the code directly from the examples.

**Actual Behaviour**
But instead i kept getting an error on line 44 return handler(req, res), which is the graphql-sse createHandler
![Screenshot 2022-12-06 at 10 23 21 AM](https://user-images.githubusercontent.com/20426361/205952438-2ae8f1be-fef2-47e8-b9a6-6088f00651cd.png)
if you go to the node_modules you'll end up here:
![Screenshot 2022-12-06 at 10 24 36 AM](https://user-images.githubusercontent.com/20426361/205952725-cbbf9293-d2d8-446a-bb17-2419011ac45c.png)

**Debug Information**
Help us debug the bug?
I am using typescript, strict mode true 

**Further Information**
Anything else you might find helpful. 
I was able to bypass not being able to start the server by adding Http2ServerRequest and Http2ServerResponse to the function createHandle, handler and the interface HadlerOptions. But the problem is out of my scrope and my be cascading to other functions im not aware of.

![Screenshot 2022-12-06 at 10 25 51 AM](https://user-images.githubusercontent.com/20426361/205953046-e0c05c29-d81e-4f05-9bc6-bab5a8316ed6.png)

Here is what that looks like:
![Screenshot 2022-12-06 at 10 38 23 AM](https://user-images.githubusercontent.com/20426361/205956093-945745b7-b3af-4755-9ca2-3993c339ac07.png)

**Comment by enisdenjo** [comment]
Hey thanks for reporting this, I will push a PR soon!
