### ISSUE TITLE
Broken persisted queries support

### ISSUE THREAD

**Issue by silvercrown07** [enisdenjo/graphql-sse#58]
Hi @enisdenjo, first of all, thank you for maintaining such an awesome project!

 I would like to report an issue related to persisted queries support.

As described in the [recipes](https://the-guild.dev/graphql/sse/recipes#server-handler-and-client-usage-with-persisted-queries): 
```ts
// 🛸 server
 
import { parse, ExecutionArgs } from 'graphql';
import { createHandler } from 'graphql-sse';
import { schema } from './my-graphql';
 
// a unique GraphQL execution ID used for representing
// a query in the persisted queries store. when subscribing
// you should use the `SubscriptionPayload.query` to transmit the id
type QueryID = string;
 
const queriesStore: Record<QueryID, ExecutionArgs> = {
  iWantTheGreetings: {
    schema, // you may even provide different schemas in the queries store
    document: parse('subscription Greetings { greetings }'),
  },
};
 
export const handler = createHandler({
  onSubscribe: (_req, params) => {
    const persistedQuery =
      queriesStore[String(params.extensions?.persistedQuery)];
    if (persistedQuery) {
      return {
        ...persistedQuery,
        variableValues: params.variables, // use the variables from the client
        contextValue: undefined,
      };
    }
 
    // for extra security only allow the queries from the store
    return [null, { status: 404, statusText: 'Not Found' }];
  },
});
```
`onSubscribe` would return a `ExecutionArgs` result, leading graphql to execute the expected resolver.

However in current implementation, the returned result from above example is treated as **ExecutionResult**, hence the resolver is not triggered.
https://github.com/enisdenjo/graphql-sse/blob/d4890f1a513ab21573c52be6ccb57c8cd14919d7/src/handler.ts#L587-L600
https://github.com/enisdenjo/graphql-sse/blob/d4890f1a513ab21573c52be6ccb57c8cd14919d7/src/handler.ts#L1107-L1110

Please let me know if I missed anything, and if more details are needed, thank you!

**Comment by enisdenjo** [comment]
Hey there, thanks for reporting! I think I know where the problem is, fix coming soon...
