### ISSUE TITLE
Subscription errors get silently discarded 

### ISSUE THREAD

**Issue by silvercrown07** [enisdenjo/graphql-sse#63]
Hi @enisdenjo, as always, appreciate your efforts in this project.

This time I would like to raise a concern on subscription error handling.

Minimum setup:

schema.ts ( adapted from [get-started](https://the-guild.dev/graphql/sse/get-started) )
```ts
import { GraphQLSchema, GraphQLObjectType, GraphQLString } from 'graphql';

/**
 * Construct a GraphQL schema and define the necessary resolvers.
 *
 * type Query {
 *   hello: String
 * }
 * type Subscription {
 *   greetings: String
 * }
 */
export const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    fields: {
      hello: {
        type: GraphQLString,
        resolve: () => 'world',
      },
    },
  }),
  subscription: new GraphQLObjectType({
    name: 'Subscription',
    fields: {
      greetings: {
        type: GraphQLString,
        subscribe: async function () {
          // instead of returning the `AsyncIterator`, an error was thrown
          throw new Error('Unexpected stuffs happened');
        },
      },
    },
  }),
});
```

server.ts ( adapted from [this example](https://github.com/enisdenjo/graphql-sse/blob/3fd31dbcae691a09fe47596e2e2fec2308ee0762/src/use/http.ts#L33-L51) )
```ts
import http from 'http';
import { createHandler } from 'graphql-sse/lib/use/http';
import { schema } from './schema';

// Create the GraphQL over SSE handler
const handler = createHandler({ schema });

// Create an HTTP server using the handler on `/graphql/stream`
const server = http.createServer(async (req, res) => {
  if (req.url.startsWith('/graphql/stream')) {
    try {
      await handler(req, res);
    } catch (error) {
      console.error(error);
      res.writeHead(500).end();

      return;
    }
    res.writeHead(404).end();
  }
});

server.listen(4000);
console.log('Listening to port 4000');
```

I was expecting the error to be captured and the response to be 500, however what I observed was that the error got silently discarded, and the response was 202.

After a bit digging, I realized the cause is:
https://github.com/enisdenjo/graphql-sse/blob/3fd31dbcae691a09fe47596e2e2fec2308ee0762/src/handler.ts#L717-L729
https://github.com/enisdenjo/graphql-sse/blob/3fd31dbcae691a09fe47596e2e2fec2308ee0762/src/handler.ts#L985-L1006

Because an error is thrown, the `prepared` result here becomes something like `{ errors: [xxx] }` ( from the `subscription` call ) and finally the 202 response gets returned.

I wonder if this behavior is intended ? if so how we're suppose to capture the errors from subscription ?

Thanks ahead for your kind answers!

**Comment by enisdenjo** [comment]
Hey @silvercrown07, thanks for asking this question! This is actually expected behaviour, operation errors from resolvers are reported to the stream instead of the operation request, both in single connection mode and distinct connection mode. [I've added a test to demonstrate this.](https://github.com/enisdenjo/graphql-sse/commit/995c4bea0231c174cbaa26ec216725872879936f)

https://github.com/enisdenjo/graphql-sse/blob/995c4bea0231c174cbaa26ec216725872879936f/src/__tests__/handler.ts#L441-L487
